In [1]:
# Import necessary libraries and packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import tree
from sklearn import linear_model
from sklearn.model_selection import KFold
#from sklearn.cross_validation import StratifiedKFold
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn import metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, explained_variance_score, r2_score
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer

In [2]:
movies = pd.read_csv("Training sheet.csv")

In [3]:
movies_df = pd.DataFrame(movies)
movies_df.head()

,id,name,display_name,production_year,movie_sequel,creative_type,source,production_method,genre,language,board_rating_reason,movie_board_rating_display_name,movie_release_pattern_display_name,total,Category
0,7950115,Avatar,Avatar,2009,0,Science Fiction,Original Screenplay,Animation/Live Action,Action,English,"For intense epic battle sequences and warfare,...",PG-13,Wide,2784,9
1,50950115,Harry Potter and the Deathly Hallows: Part II,Harry Potter and the Deathly Hallows: Part II,2011,1,Fantasy,Based on Fiction Book/Short Story,Animation/Live Action,Adventure,English,for some sequences of intense action violence ...,PG-13,Wide,1328,9
2,119870115,Transformers 3,Transformers: Dark of the Moon,2011,1,Science Fiction,Based on TV,Animation/Live Action,Action,English,for intense prolonged sequences of sci-fi acti...,PG-13,Wide,1124,9
3,119590115,Toy Story 3,Toy Story 3,2010,1,Kids Fiction,Original Screenplay,Digital Animation,Adventure,English,General,G,Wide,1064,9
4,91700115,Pirates of the Caribbean 4,Pirates of the Caribbean: On Stranger Tides,2011,1,Fantasy,Based on Theme Park Ride,Live Action,Adventure,English,for intense sequences of action/adventure viol...,PG-13,Wide,1044,9

In [4]:
# import ast

# def eval_code(code):
#     parsed = ast.parse(code, mode='eval')
#     fixed = ast.fix_missing_locations(parsed)
#     compiled = compile(fixed, '<string>', 'eval')
#     eval(compiled)

# features = ['name', 'display_name', 'creative_type', 'source', 'production_method', 'genre', 'language',
#             'board_rating_reason', 'movie_board_rating_display_name', 'movie_release_pattern_display_name']
# for feature in features:
#     movies_df[feature] = eval_code(movies_df[feature])

In [5]:
# Function to convert all strings to lower case and strip names of spaces
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace("/", ""))
        else:
            if isinstance(x, str):
                return str.lower(x.replace(",", ""))
            else:
                return ''

In [6]:
# Parse the stringified features into their corresponding python objects
from ast import literal_eval

features = ['name', 'display_name', 'creative_type', 'source', 'production_method', 'genre', 'language',
            'board_rating_reason', 'movie_board_rating_display_name', 'movie_release_pattern_display_name']
# for feature in features:
#     movies_df[feature] = movies_df[feature].apply(literal_eval)
    
for feature in features:
    movies_df[feature] = movies_df[feature].apply(clean_data)

In [7]:
movies_df.columns

Index(['id', 'name', 'display_name', 'production_year', 'movie_sequel',
       'creative_type', 'source', 'production_method', 'genre', 'language',
       'board_rating_reason', 'movie_board_rating_display_name',
       'movie_release_pattern_display_name', 'total', 'Category'],
      dtype='object')

## Logistic Regression Classifier Model

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from math import sqrt
import seaborn as sns

In [9]:
# target = movies_df['Category']
# movies_df = movies_df.drop('Category', axis = 1)
movies_df.keys()

Index(['id', 'name', 'display_name', 'production_year', 'movie_sequel',
       'creative_type', 'source', 'production_method', 'genre', 'language',
       'board_rating_reason', 'movie_board_rating_display_name',
       'movie_release_pattern_display_name', 'total', 'Category'],
      dtype='object')

In [10]:

# Use Pandas get_dummies to convert categorical data

y = movies_df["Category"].values.reshape(-1, 1)
# movies_df = movies_df.drop(['Category'])
X = movies_df
X.creative_type = X.creative_type.map(lambda x: x.strip())
X.source = X.source.map(lambda x: x.strip())
X.production_method = X.production_method.map(lambda x: x.strip())
X.genre = X.genre.map(lambda x: x.strip())
X.language = X.language.map(lambda x: x.strip())
X.board_rating_reason = X.board_rating_reason.map(lambda x: x.strip())
X.movie_board_rating_display_name = X.movie_board_rating_display_name.map(lambda x: x.strip())

df_onehot = pd.get_dummies(X)
df_onehot.head()
print(X.shape, y.shape)

(1196, 15) (1196, 1)

In [11]:
df_onehot.head()

,id,production_year,movie_sequel,total,Category,"name_10,000 b.c.",name_12 rounds,name_127 hours,name_1408,name_2010 oscar shorts,...,movie_board_rating_display_name_pg,movie_board_rating_display_name_pg-13,movie_board_rating_display_name_r,movie_release_pattern_display_name_exclusive,movie_release_pattern_display_name_expands wide,movie_release_pattern_display_name_imax,movie_release_pattern_display_name_limited,movie_release_pattern_display_name_oscar qualifying run,movie_release_pattern_display_name_special engagement,movie_release_pattern_display_name_wide
0,7950115,2009,0,2784,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,50950115,2011,1,1328,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
2,119870115,2011,1,1124,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,119590115,2010,1,1064,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,91700115,2011,1,1044,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [12]:
X_2 = df_onehot.copy()
X_2.head()

,id,production_year,movie_sequel,total,Category,"name_10,000 b.c.",name_12 rounds,name_127 hours,name_1408,name_2010 oscar shorts,...,movie_board_rating_display_name_pg,movie_board_rating_display_name_pg-13,movie_board_rating_display_name_r,movie_release_pattern_display_name_exclusive,movie_release_pattern_display_name_expands wide,movie_release_pattern_display_name_imax,movie_release_pattern_display_name_limited,movie_release_pattern_display_name_oscar qualifying run,movie_release_pattern_display_name_special engagement,movie_release_pattern_display_name_wide
0,7950115,2009,0,2784,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,50950115,2011,1,1328,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
2,119870115,2011,1,1124,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,119590115,2010,1,1064,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,91700115,2011,1,1044,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [13]:
# Split data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_2, y, random_state=42)

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
#Fit the model
y_train = y_train.ravel()
classifier.fit(X_train, y_train)

print(y_train.shape)
#Validate Model using test data
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

(897,)
Training Data Score: 0.2028985507246377
Testing Data Score: 0.21070234113712374

In [16]:
# Make predictions with the hypertuned model
predictions = classifier.predict(X_test)
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=['9', '8', '7', '6', '5', '4', '3', '2', '1']))

             precision    recall  f1-score   support

          9       0.00      0.00      0.00        33
          8       0.00      0.00      0.00        66
          7       0.21      1.00      0.35        63
          6       0.00      0.00      0.00        53
          5       0.00      0.00      0.00        37
          4       0.00      0.00      0.00        19
          3       0.00      0.00      0.00        16
          2       0.00      0.00      0.00        10
          1       0.00      0.00      0.00         2

avg / total       0.04      0.21      0.07       299

C:\Users\dinot\AppData\Local\conda\conda\envs\pythondata\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [18]:
from sklearn.metrics import r2_score
print('Variance score: %.2f' % r2_score(y_test, predictions))

Variance score: -0.10

In [19]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=100)

In [20]:
kmeans.fit(X_2)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=100, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [21]:
predicted_clusters = kmeans.predict(X_2)
predicted_clusters
cluster_labels=[]
j=0
for i in predicted_clusters:
    cluster_labels.append([i,y[j]])
    j+=1
cluster_labels
testdf=pd.DataFrame(cluster_labels)
testdf=testdf.rename(columns={0: 'Class', 1: 'Category'})
testdf=testdf.sort_values('Class', ascending=True)
testdf=testdf.set_index("Class")
#testdf=testdf.groupby("Class")

In [22]:
centers = kmeans.cluster_centers_
labels = kmeans.labels_
print(labels)

[42 91 53 ...  7 69 17]

In [23]:
testdf.to_csv("Training_Logistic_Kmeans_clusters.csv")

In [24]:
# movies_score = pd.read_csv("Scoring sheet.csv")
test=X_2[:1]

test

,id,production_year,movie_sequel,total,Category,"name_10,000 b.c.",name_12 rounds,name_127 hours,name_1408,name_2010 oscar shorts,...,movie_board_rating_display_name_pg,movie_board_rating_display_name_pg-13,movie_board_rating_display_name_r,movie_release_pattern_display_name_exclusive,movie_release_pattern_display_name_expands wide,movie_release_pattern_display_name_imax,movie_release_pattern_display_name_limited,movie_release_pattern_display_name_oscar qualifying run,movie_release_pattern_display_name_special engagement,movie_release_pattern_display_name_wide
0,7950115,2009,0,2784,9,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [25]:
kmeans.predict(test)

array([42])

In [26]:
kmeans.score(test)

-5413209605.828125

In [27]:
import pickle
filename = 'kmeans_movies_cluster.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [28]:
# scoring = pd.read_csv("Scoring Sheet.csv")
# # scoredf = scoring[:1]

In [29]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(test)
print("The test data belongs to Class: ", result)
df=testdf.loc[testdf.index==result[0]]

The test data belongs to Class:  [42]

In [30]:
# Use Pandas get_dummies to convert categorical data

# y = movies_df["Category"].values.reshape(-1, 1)
# movies_df = movies_df.drop(['Category'])
# X_score = scoredf
# scoredf_onehot = pd.get_dummies(scoring)
# scoredf_onehot.head()
# print(X_score.shape, y.shape)

In [31]:
# X_score = scoredf_onehot.copy()

In [32]:
# X_score.head()

In [33]:
# loaded_model = pickle.load(open(filename, 'rb'))
# result = loaded_model.predict(X_score)
# print("The test data belongs to Class: ", result)
# df=scoredf.loc[scoredf.index==result[0]]

print("The categories are:",df.values)

The categories are: [[array([3], dtype=int64)]
 [array([2], dtype=int64)]
 [array([1], dtype=int64)]
 [array([2], dtype=int64)]
 [array([2], dtype=int64)]
 [array([1], dtype=int64)]
 [array([1], dtype=int64)]
 [array([3], dtype=int64)]
 [array([2], dtype=int64)]
 [array([2], dtype=int64)]
 [array([9], dtype=int64)]
 [array([4], dtype=int64)]
 [array([5], dtype=int64)]
 [array([4], dtype=int64)]
 [array([4], dtype=int64)]
 [array([6], dtype=int64)]
 [array([4], dtype=int64)]]